### ISSUE TITLE
node-sass breaks when running in Docker container

### ISSUE THREAD

**Issue by adamkdean** [kingsreach/kingsreach-online#14]
For some reason, while `npm install` runs fine on `docker build`, the application fails when running due to the following issue:

```
> node --harmony dist/index.js

fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/var/www/node_modules/node-sass-middleware/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/var/www/node_modules/node-sass-middleware/node_modules/node-sass/lib/extensions.js:119:13)
    at foundBinariesList (/var/www/node_modules/node-sass-middleware/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/node_modules/node-sass-middleware/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/node_modules/node-sass-middleware/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/var/www/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:15:28)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/node_modules/node-sass-middleware/middleware.js:3:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm info kingsreach-online@0.0.0 Failed to exec start script
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! kingsreach-online@0.0.0 start: `node --harmony dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kingsreach-online@0.0.0 start script 'node --harmony dist/index.js'.
npm ERR! This is most likely a problem with the kingsreach-online package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony dist/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls kingsreach-online
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/npm-debug.log

```

**Comment by adamkdean** [comment]
FWIW, this runs fine locally without Docker

**Comment by adamkdean** [comment]
```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

```

**Comment by adamkdean** [comment]
~~Testing locally now.~~

Not on this dog slow public WiFi I won't be.

**Comment by adamkdean** [comment]
Locally, node-sass has vendor:

```
$ ls -l node_modules/node-sass-middleware/node_modules/node-sass/
total 80
-rw-r--r--   1 adam  staff   1210 16 Jun 12:19 CHANGELOG.md
-rw-r--r--   1 adam  staff   1063 19 Apr 10:55 LICENSE
-rw-r--r--   1 adam  staff  23725 16 Jun 12:18 README.md
drwxr-xr-x   3 adam  staff    102 16 Jun 12:18 bin
-rw-r--r--   1 adam  staff   2326 19 Apr 10:55 binding.gyp
drwxr-xr-x   6 adam  staff    204  1 Jul 17:18 lib
drwxr-xr-x  16 adam  staff    544  1 Jul 17:18 node_modules
-rw-r--r--   1 adam  staff   3150  1 Jul 17:18 package.json
drwxr-xr-x   6 adam  staff    204  1 Jul 17:18 scripts
drwxr-xr-x  15 adam  staff    510  1 Jul 17:18 src
drwxr-xr-x   3 adam  staff    102  1 Jul 17:18 vendor
```

But within the Docker container, it doesn't:

```
root@4915596c0f1d:/var/www# ls -l node_modules/node-sass-middleware/node_modules/node-sass/
total 60
-rw-r--r--  1 root root  1210 Jun 16 11:19 CHANGELOG.md
-rw-r--r--  1 root root  1063 Apr 19 09:55 LICENSE
-rw-r--r--  1 root root 23725 Jun 16 11:18 README.md
drwxr-xr-x  2 root root  4096 Jun 16 11:18 bin
-rw-r--r--  1 root root  2326 Apr 19 09:55 binding.gyp
drwxr-xr-x  2 root root  4096 Jul  2 16:15 lib
drwxr-xr-x 16 root root  4096 Jul  2 16:16 node_modules
-rw-r--r--  1 root root  3106 Jul  2 16:16 package.json
drwxr-xr-x  2 root root  4096 Jul  2 16:16 scripts
drwxr-xr-x  4 root root  4096 Jul  2 16:16 src
```

**Comment by adamkdean** [comment]
Fixed by upgrading npm to 3.x:

```
$ docker logs 3d4e6
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v4.2.6
npm info lifecycle kingsreach-online@0.0.0~prestart: kingsreach-online@0.0.0

> kingsreach-online@0.0.0 prestart /var/www
> gulp

[17:15:33] Using gulpfile /var/www/gulpfile.js
[17:15:33] Starting 'clean'...
[17:15:33] Finished 'clean' after 8.86 ms
[17:15:33] Starting 'transpile'...
[17:15:33] Finished 'transpile' after 456 ms
[17:15:33] Starting 'default'...
[17:15:33] Finished 'default' after 14 μs
npm info lifecycle kingsreach-online@0.0.0~start: kingsreach-online@0.0.0

> kingsreach-online@0.0.0 start /var/www
> node --harmony dist/index.js

Listening on port 8016

```
